public class AccRecordsDisplay 
{
 /*   public Account getAccountDetails(Id  accId){
         List<Account> ar=[Select Name,AccountNumber,BillingAddress,Industry,Rating from Account where Id= accId;
                           if(ar.size()=0){
                               
                           }else {
                               
                           }
    }
    public void accRecords()
    {
        List<Account> ar=[Select Name,AccountNumber,BillingAddress,Industry,Rating from Account where name='S%'];
        
        //List<Account> la=new List<Account>();
        //la.add(A.Name);
        for(Account a: ar)
        {
            System.debug('Records fetched are: '+ar);
        }
        //System.debug(ar);
    }*/

}